// <auto-generated />
using System;
using CookbookProject.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CookbookProject.Migrations
{
    [DbContext(typeof(CookbookProjectContext))]
    partial class CookbookProjectContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CookbookProject.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25)
                        .IsUnicode(true);

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Pasta"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Fast Food"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Dessert"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Pastry"
                        },
                        new
                        {
                            Id = 5,
                            Title = "Stew"
                        });
                });

            modelBuilder.Entity("CookbookProject.Models.Cuisine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(25)")
                        .HasMaxLength(25)
                        .IsUnicode(true);

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Cuisine");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Mexican"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Italian"
                        },
                        new
                        {
                            Id = 3,
                            Title = "American"
                        },
                        new
                        {
                            Id = 4,
                            Title = "British"
                        },
                        new
                        {
                            Id = 5,
                            Title = "Indian"
                        });
                });

            modelBuilder.Entity("CookbookProject.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(true);

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "All-purpose Flour"
                        },
                        new
                        {
                            Id = 2,
                            Title = "Cherries"
                        },
                        new
                        {
                            Id = 3,
                            Title = "Eggs"
                        },
                        new
                        {
                            Id = 4,
                            Title = "Sugar"
                        },
                        new
                        {
                            Id = 5,
                            Title = "Milk"
                        },
                        new
                        {
                            Id = 6,
                            Title = "Spaghetti"
                        },
                        new
                        {
                            Id = 7,
                            Title = "Garlic"
                        },
                        new
                        {
                            Id = 8,
                            Title = "Tomatoes"
                        },
                        new
                        {
                            Id = 9,
                            Title = "Beef"
                        },
                        new
                        {
                            Id = 10,
                            Title = "Parmesan"
                        },
                        new
                        {
                            Id = 11,
                            Title = "Tortillas"
                        },
                        new
                        {
                            Id = 12,
                            Title = "Salmon"
                        });
                });

            modelBuilder.Entity("CookbookProject.Models.Measurement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Consistency")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(true);

                    b.Property<int?>("IngredientId")
                        .HasColumnType("int");

                    b.Property<string>("Quantity")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(true);

                    b.Property<int?>("RecipeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecipeId");

                    b.ToTable("Measurements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IngredientId = 11,
                            Quantity = "3",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Consistency = "fillet",
                            IngredientId = 12,
                            Quantity = "200 gr",
                            RecipeId = 1
                        },
                        new
                        {
                            Id = 3,
                            IngredientId = 1,
                            Quantity = "250 gr",
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 4,
                            Consistency = "frozen",
                            IngredientId = 2,
                            Quantity = "100 gr",
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 5,
                            Consistency = "beaten",
                            IngredientId = 3,
                            Quantity = "4",
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 6,
                            IngredientId = 4,
                            Quantity = "150 gr",
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 7,
                            Consistency = "Skimmed",
                            IngredientId = 5,
                            Quantity = "300 ml",
                            RecipeId = 2
                        },
                        new
                        {
                            Id = 8,
                            IngredientId = 6,
                            Quantity = "100 gr",
                            RecipeId = 3
                        },
                        new
                        {
                            Id = 9,
                            Consistency = "crushed",
                            IngredientId = 7,
                            Quantity = "1 clove",
                            RecipeId = 3
                        },
                        new
                        {
                            Id = 10,
                            IngredientId = 8,
                            Quantity = "1 can",
                            RecipeId = 3
                        },
                        new
                        {
                            Id = 11,
                            Consistency = "minced",
                            IngredientId = 9,
                            Quantity = "200 gr",
                            RecipeId = 3
                        },
                        new
                        {
                            Id = 12,
                            IngredientId = 10,
                            Quantity = "2 teaspoons",
                            RecipeId = 3
                        });
                });

            modelBuilder.Entity("CookbookProject.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("CuisineId")
                        .HasColumnType("int");

                    b.Property<string>("ImagePath")
                        .HasColumnType("varchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(false);

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(800)")
                        .HasMaxLength(800)
                        .IsUnicode(true);

                    b.Property<string>("PrepTime")
                        .HasColumnType("nvarchar(15)")
                        .HasMaxLength(15)
                        .IsUnicode(true);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30)
                        .IsUnicode(true);

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("CuisineId");

                    b.HasIndex("UserId");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 2,
                            CuisineId = 1,
                            Instructions = "Instructions for Fish Tacos",
                            PrepTime = "25 min",
                            Title = "Fish Tacos",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 3,
                            CuisineId = 3,
                            Instructions = "Instructions for Cherry Cobbler",
                            PrepTime = "45 min",
                            Title = "Cherry Cobbler",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CuisineId = 2,
                            Instructions = "Instructions for Beef Ragu",
                            PrepTime = "55 min",
                            Title = "Beef Ragu",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("CookbookProject.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:IdentityIncrement", 1)
                        .HasAnnotation("SqlServer:IdentitySeed", 1)
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(320)")
                        .HasMaxLength(320)
                        .IsUnicode(false);

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20)
                        .IsUnicode(true);

                    b.HasKey("Id");

                    b.HasIndex("Email", "Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "karajanovb@yahoo.com",
                            Password = new byte[] { 49, 162, 213, 40, 38, 131, 237, 179, 162, 44, 86, 95, 25, 154, 169, 111, 185, 255, 179, 16, 122, 243, 90, 173, 146, 238, 28, 213, 103, 207, 194, 93 },
                            Username = "UserOne"
                        });
                });

            modelBuilder.Entity("CookbookProject.Models.Measurement", b =>
                {
                    b.HasOne("CookbookProject.Models.Ingredient", "Ingredient")
                        .WithMany("Recipes")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CookbookProject.Models.Recipe", "Recipe")
                        .WithMany("Ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("CookbookProject.Models.Recipe", b =>
                {
                    b.HasOne("CookbookProject.Models.Category", "Category")
                        .WithMany("Recipes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CookbookProject.Models.Cuisine", "Cuisine")
                        .WithMany("Recipes")
                        .HasForeignKey("CuisineId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CookbookProject.Models.User", "User")
                        .WithMany("Recipes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
